name: Build and Deploy to Azure Web App - Docker

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the deployment on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: gccds.azurecr.io  # e.g., myregistry.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t gccds.azurecr.io/my-nestjs-app:${{ github.sha }} .
        docker push gccds.azurecr.io/my-nestjs-app:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: gc-cds-api-versioning-poc-v2  # Replace with your Azure Web App name
        images: gccds.azurecr.io/my-nestjs-app:${{ github.sha }}
