name: Build and Deploy to Azure Web App - Docker

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the deployment on
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: gccds.azurecr.io  # e.g., myregistry.azurecr.io
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cat Dockerfile
        docker build -t gccds.azurecr.io/my-nestjs-app:${{ github.sha }} .
        docker image inspect gccds.azurecr.io/my-nestjs-app:${{ github.sha }}
        docker push gccds.azurecr.io/my-nestjs-app:${{ github.sha }}

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: gc-cds-api-versioning-poc-v3  # Replace with your Azure Web App name
        images: gccds.azurecr.io/my-nestjs-app:${{ github.sha }}
